services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  database_test:
    image: postgres
    container_name: database_test
    restart: always
    ports: 
      - 5555:5555
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=9121
      - POSTGRES_DB=rentx_test
    command: -p 5555
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local

